//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industrial_Informatics_Project.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chimpanzee_Stats
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<double> game_time { get; set; }
        public Nullable<double> avg_memory_time { get; set; }
        public Nullable<double> avg_solve_time { get; set; }
        public string date { get; set; }
        public Nullable<int> difficulty { get; set; }
    }
}
