//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industrial_Informatics_Project.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string question_text { get; set; }
        public string question_options { get; set; }
        public string question_answer { get; set; }
        public Nullable<int> difficulty { get; set; }
    }
}
