//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industrial_Informatics_Project.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Stats
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> corect_answers { get; set; }
        public Nullable<int> incorect_answers { get; set; }
        public Nullable<float> time_remaining { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> difficulty { get; set; }
    }
}
